### ISSUE TITLE
License

### ISSUE THREAD

**Issue by TheCthulhuKid** [confirm/django-fulltext-search#2]
You might want to add a license, just to make sure it can be used properly. You can have a look [here](https://help.github.com/articles/open-source-licensing/) for some help =)

**Comment by domibarton** [comment]
Well, what kind of license would you like? ;)

I always go for GPLv3 or MIT. However, GPLv3 is more restrictive in terms of usage - you might have to make your project as well open-source / GPLv3 compliant to meet the GPLv3 requirements.

**Comment by TheCthulhuKid** [comment]
Thanks for the reply =)

I am, unfortunately, working on proprietary code at the moment. So I have been reading a lot about licenses lol So I just thought I'd say so that you and users are covered =D

Love the code by the way!
